blank_issues_enabled: false
contact_links:
  - name: .NET MAUI Community Support
    url: https://techcommunity.microsoft.com/t5/app-development/bd-p/app-dev
    about: Please ask and answer questions here.
